# https://hub.docker.com/_/centos/
# https://hub.docker.com/_/fedora/
ARG IMAGE
ARG IMAGE_VER
FROM $IMAGE:$IMAGE_VER
LABEL MAINTAINER Eric Martin <eric@ericdoesinfosec.com>

ARG SSHCLIENT
ARG SSHCLIENT_VER
# Install the SSH client
RUN yum -y install $SSHCLIENT-$SSHCLIENT_VER && yum clean all
